### ISSUE TITLE
PMR446?

### ISSUE THREAD

**Issue by arazumny** [ways/chirp-marine-vhf-no#1]
Ble du noensinne ferdig med Sikringsradio-CSVen? Og har du sett på å lage en CDV for PMR 446-kanalene?

**Comment by ways** [comment]
Hei. Kom ikke lengre med sikring, nei. Det finnes allerede offisiell liste for PMR. Mener den ligger i menyen i Chirp.

**Comment by arazumny** [comment]
Humm. Det må jeg sjekke når jeg er tilbake ved maskinen. Det er litt andre frekvensbånd i Norge enn i USA.

**Comment by arazumny** [comment]
Da har jeg sjekket, jeg antar det er KDR 444-fila du tenker på? Den er ikke gyldig for PMR 446-kanalene. Jeg mekker noe i forken min - skal bare få programmeringskabelen til å fungere først - og kjører inn en pull-request, jeg.
